### ISSUE TITLE
Consider allowing to specify GIT branch

### ISSUE THREAD

**Issue by hopkins-tk** [elmariofredo/relax#8]
I would like to test my deployment using Relax on a staging cluster before rolling the change to production.

So I was thinking about creating a branch and if deployment is running fine in staging, merging the change to production branch.

**Comment by elmariofredo** [comment]
I agree that we should allow to specify branch, we could probably add third argument which will default to `master` WDYT?

**Comment by elmariofredo** [comment]
Closed in version `v0.21`
